### ISSUE TITLE
Missing interval-struct.rkt

### ISSUE THREAD

**Issue by soegaard** [ntoronto/racket#15]
Hi @ntoronto 

I think you have forgotten to add the file:

   private/interval/interval-struct.rkt

/Jens Axel

**Comment by ntoronto** [comment]
On 10/15/2012 08:21 AM, Jens Axel Søgaard wrote:

> Hi @ntoronto https://github.com/ntoronto
> 
> I think you have forgotten to add the file:
> 
> private/interval/interval-struct.rkt

Sorry about that! I actually took it out, since I don't want intervals 
until we have something like generics in TR.

I'd update my github repository to fix it, but since merging from 
upstream, my local repo has worse problems. There's an error in TR's 
inference in certain cases, which I can't work around. I could branch 
and fix, but I'm in the middle of something. It'd probably be faster for 
both of us if you removed the dangling references to interval modules in 
your repo and either sent a pull request or waited for my next huge 
batch of commits.

Sorry again. I didn't mean for broken-ness to spread past my own stuff.

Neil ⊥

**Comment by soegaard** [comment]
Hi Neil,

No worries. The only breakage I see is an error message
from "raco setup". Since interval.rkt is not used from
any other of the other modules (I grepped just now)
just wait till your repository is in a sane state again.

/Jens Axel

2012/10/16 Neil Toronto notifications@github.com

> On 10/15/2012 08:21 AM, Jens Axel Søgaard wrote:
> 
> > Hi @ntoronto https://github.com/ntoronto
> > 
> > I think you have forgotten to add the file:
> > 
> > private/interval/interval-struct.rkt
> 
> Sorry about that! I actually took it out, since I don't want intervals
> until we have something like generics in TR.
> 
> I'd update my github repository to fix it, but since merging from
> upstream, my local repo has worse problems. There's an error in TR's
> inference in certain cases, which I can't work around. I could branch
> and fix, but I'm in the middle of something. It'd probably be faster for
> both of us if you removed the dangling references to interval modules in
> your repo and either sent a pull request or waited for my next huge
> batch of commits.
> 
> Sorry again. I didn't mean for broken-ness to spread past my own stuff.
> 
> Neil ⊥
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ntoronto/racket/issues/15#issuecomment-9506770.

## 

## 

Jens Axel Søgaard
